import "./globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "Pragmatic Digital",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
